//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryStore.Helper.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JewelleryStore.Helper.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UserNameText {
            get {
                return ResourceManager.GetString("UserNameText", resourceCulture);
            }
        }
        
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        internal static string GoldPriceConstant {
            get {
                return ResourceManager.GetString("GoldPriceConstant", resourceCulture);
            }
        }
        
        internal static string WeightConstant {
            get {
                return ResourceManager.GetString("WeightConstant", resourceCulture);
            }
        }
        
        internal static string TotalPriceConstant {
            get {
                return ResourceManager.GetString("TotalPriceConstant", resourceCulture);
            }
        }
        
        internal static string DiscountConstant {
            get {
                return ResourceManager.GetString("DiscountConstant", resourceCulture);
            }
        }
        
        internal static string CalculateConstant {
            get {
                return ResourceManager.GetString("CalculateConstant", resourceCulture);
            }
        }
        
        internal static string PrinttoScreenConstant {
            get {
                return ResourceManager.GetString("PrinttoScreenConstant", resourceCulture);
            }
        }
        
        internal static string PrinttofileConstant {
            get {
                return ResourceManager.GetString("PrinttofileConstant", resourceCulture);
            }
        }
        
        internal static string PrinttoPaperConstant {
            get {
                return ResourceManager.GetString("PrinttoPaperConstant", resourceCulture);
            }
        }
        
        internal static string WelcomeConstant {
            get {
                return ResourceManager.GetString("WelcomeConstant", resourceCulture);
            }
        }
        
        internal static string UserConstant {
            get {
                return ResourceManager.GetString("UserConstant", resourceCulture);
            }
        }
        
        internal static string PrevilegedConstant {
            get {
                return ResourceManager.GetString("PrevilegedConstant", resourceCulture);
            }
        }
        
        internal static string ValidInputsConstant {
            get {
                return ResourceManager.GetString("ValidInputsConstant", resourceCulture);
            }
        }
        
        internal static string PriceWeightConstant {
            get {
                return ResourceManager.GetString("PriceWeightConstant", resourceCulture);
            }
        }
        
        internal static string CloseConstant {
            get {
                return ResourceManager.GetString("CloseConstant", resourceCulture);
            }
        }
        
        internal static string SavedToFileConstant {
            get {
                return ResourceManager.GetString("SavedToFileConstant", resourceCulture);
            }
        }
        
        internal static string OkayConstant {
            get {
                return ResourceManager.GetString("OkayConstant", resourceCulture);
            }
        }
        
        internal static string BillingConstant {
            get {
                return ResourceManager.GetString("BillingConstant", resourceCulture);
            }
        }
        
        internal static string LoginErrorConstant {
            get {
                return ResourceManager.GetString("LoginErrorConstant", resourceCulture);
            }
        }
        
        internal static string LoginErrorMessageConstant {
            get {
                return ResourceManager.GetString("LoginErrorMessageConstant", resourceCulture);
            }
        }
    }
}
